-- Active: 1752796799447@@127.0.0.1@3306@acosa

--Tabla de Productos
  CREATE TABLE `products` (
    `productId` INT(11) NOT NULL AUTO_INCREMENT,
    `productName` VARCHAR(255) NOT NULL,
    `productDescription` TEXT NOT NULL,
    `productPrice` DECIMAL(10,2) NOT NULL,
    `productImgUrl` VARCHAR(255) NOT NULL,
    `productStatus` CHAR(3) NOT NULL,
    `categoryId` INT(11) NOT NULL,
    `stock` INT(11) NOT NULL DEFAULT 0,
    PRIMARY KEY (`productId`)
  ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;


--Tabla de Categorias
  CREATE TABLE `categories` (
    `categoryId` int(11) NOT NULL AUTO_INCREMENT,
    `categoryName` varchar(100) NOT NULL,
    PRIMARY KEY (`categoryId`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


--Tabla de Ventas
  CREATE TABLE `sales` (
    `saleId` INT(11) NOT NULL AUTO_INCREMENT,
    `productId` INT(11) NOT NULL,
    `discountPercent` DECIMAL(5,2) NOT NULL COMMENT 'Porcentaje de descuento (ej: 20.00 para 20%)',
    `saleStart` DATETIME NOT NULL,
    `saleEnd` DATETIME NOT NULL,
    PRIMARY KEY (`saleId`),
    KEY `fk_sales_products_idx` (`productId`),
    CONSTRAINT `fk_sales_products` FOREIGN KEY (`productId`) REFERENCES `products` (`productId`) ON DELETE CASCADE ON UPDATE CASCADE
  ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;


  --Datos en la tabla de Productos
  INSERT INTO `products` (`productId`, `productName`, `productDescription`, `productPrice`, `productImgUrl`, `productStatus`, `categoryId`, `stock`) VALUES
  (1, 'Marcador Acrilico Deli 6 Colores', 'Descubre la magia de la creatividad con este paquete de 6 marcadores acrílicos Deli, ideales para darle un toque brillante y metálico a tus proyectos escolares.', 79.90, 'https://acosa.com.hn/wp-content/uploads/2025/02/HM114-B.webp', 'ACT', 1, 15),
  (2, 'Mochila Genial Max Diseños Unisex', 'Disfruta de la comodidad y estilo, con un diseño moderno y funcional, esta mochila es perfecta para llevar todas tus pertenencias de forma segura y organizada.', 487.80, 'https://acosa.com.hn/wp-content/uploads/2024/12/GEX-MEU2404.webp', 'ACT', 1, 10),
  (3, 'Cuaderno #3 3 Materias Genial Diseños Femeninos', 'Experimenta la combinación perfecta de estilo y funcionalidad. Con sus diseños femeninos únicos, este cuaderno te ayudará a mantenerte organizada y creativa a la vez.', 49.92, 'https://acosa.com.hn/wp-content/uploads/2022/11/A45654.jpg', 'ACT', 1, 30),
  (4, 'Barra Adhesiva 21Gr Uhu', 'Ideal para tus proyectos escolares, manualidades o trabajos de oficina. Su fórmula de secado rápido garantiza una adhesión fuerte y limpia.', 41.88, 'https://acosa.com.hn/wp-content/uploads/2021/03/A1222.webp', 'ACT', 1, 40),
  (5, 'Acordeon Plastico Deli Tamaño Carta 13 Divisiones Vertical', 'Este práctico acordeón de plástico tamaño carta te ayudará a mantener tus documentos organizados de manera eficiente y ordenada. Con 13 divisiones verticales, podrás clasificar tus papeles de forma sencilla y rápida.', 205.00, 'https://acosa.com.hn/wp-content/uploads/2023/10/E5556.webp', 'ACT', 2, 20),
  (6, 'Grapadora Stanley Bostitch Tira Completa B660 Negra', 'Engrapador con tecnología anti-atasco para engrapado suave, dos funciones (temporal y estándar), indicador de grapas y remachador ajustable para 210 grapas estándar.', 206.00, 'https://acosa.com.hn/wp-content/uploads/2021/03/B660-BLK.webp', 'ACT', 2, 25),
  (7, 'Tablero T/Carta Acrimet Gancho Metal', 'Tablero tipo carta, fabricado en metal resistente, diseñado para uso en oficinas, talleres o espacios industriales. Ideal para organizar documentos, notas o materiales de trabajo, ofreciendo durabilidad y funcionalidad gracias a su construcción sólida y acabado de calidad.', 70.00, 'https://acosa.com.hn/wp-content/uploads/2021/08/A30930.png', 'ACT', 2, 50),
  (8, 'Dispensador Tape Deli 210Mm Surt Negro/Azul', 'Este dispensador de cinta de gran tamaño es la solución perfecta para mantener tus documentos organizados en la oficina. Con un diseño moderno, este producto es fácil de usar y ahorra tiempo en el embalaje de paquetes. Además, su tamaño grande garantiza que no te quedes sin cinta cuando más la necesitas.', 146.10, 'https://acosa.com.hn/wp-content/uploads/2022/11/E816.jpg', 'ACT', 2, 35),
  (9, 'Bombillo Inteligente Led Wifi Nexxt Rgb A19 Multicolor', 'Nunca fue tan fácil darle un toque personal a tu hogar con la iluminación de Nexxt. Disfruta de ambientes únicos y multicolor creados por ti, decide a qué hora se encienden o apagan las luces y mucho más, todo esto desde tu celular y con comandos de voz.', 205.00, 'https://acosa.com.hn/wp-content/uploads/2025/04/NHB-C110M.webp', 'ACT', 3, 12),
  (10, 'Camara Inteligente 2K 3Mp Para Interior Domo Tp-Link', 'Cámara 2K con visión panorámica 360º, visión nocturna hasta 9 metros, detección de movimiento con alertas, alarma de luz y sonido, audio bidireccional, almacenamiento seguro hasta 512GB, y control por voz compatible con Google Assistant y Alexa.', 990.00, 'https://acosa.com.hn/wp-content/uploads/2024/03/Tapo-C210.webp', 'ACT', 3, 8),
  (11, 'Cerradura Inteligente Wifi Negro Nexxt.', 'Cerradura inteligente con conectividad WiFi, diseño moderno en negro, que permite control remoto y acceso seguro a tu hogar desde tu smartphone. Fácil instalación y compatible con asistentes de voz.', 2800.00, 'https://acosa.com.hn/wp-content/uploads/2023/06/A71785.webp', 'ACT', 3, 6),
  (12, 'Difusor De Aroma Inteligente Wifi Nexxt', 'Difusor de aroma inteligente WiFi Nexxt NHA-A600 – Controla aromas desde tu móvil para un ambiente relajante y personalizado.', 1345.01, 'https://acosa.com.hn/wp-content/uploads/2021/06/NHA-A600.png', 'ACT', 3, 5),
  (13, 'Audifono Redragon Gaming Hylas 3.5Mm Rosa Con Microfono Rgb H260P', 'Los Hylas son auriculares estéreo con conexión de 3,5 mm y diafragmas de neodimio de 50 mm que ofrecen un sonido claro y preciso, con aislamiento pasivo para una experiencia inmersiva.', 590.00, 'https://acosa.com.hn/wp-content/uploads/2022/02/H260p-RGB.jpg', 'ACT', 4, 18),
  (14, 'Control Gaming Inalambrico Marvo Gt-88 Trasnp Rgb', 'Mando inalámbrico compatible con Android, iOS, PC, PS3, PS4 y Nintendo Switch. Diseño ergonómico con materiales antideslizantes y resistentes al sudor. Joystick 3D de alta durabilidad (500,000 usos). Soporte para móvil hasta 8.5 cm. Uso continuo de 8-12 horas.', 755.00, 'https://acosa.com.hn/wp-content/uploads/2025/07/GT-88.webp', 'ACT', 4, 13),
  (15, 'Alfombra Para Silla Trust Gaming Negro Gxt 715', 'Alfombra para silla Trust Gaming GXT 715, color negro, diseñada para proteger el suelo y facilitar el movimiento de la silla con estilo y durabilidad.', 644.00, 'https://acosa.com.hn/wp-content/uploads/2021/09/22524-1.png', 'ACT', 4, 9),
  (16, 'Disipador De Calor Laptop Marvo Gaming Usb Negro Fn-40', 'Disipador de calor para laptop Marvo Gaming USB FN-40, diseñado para evitar el sobrecalentamiento durante largas sesiones. Compacto, ligero y fácil de usar con conexión USB. Ideal para mantener tu portátil fresco y mejorar su rendimiento.', 595.00, 'https://acosa.com.hn/wp-content/uploads/2022/02/FN-40.jpg', 'ACT', 4, 11),
  (17, 'Celular Honor X7C 6.8 8GB-256GB Verde', 'Este dispositivo tiene una pantalla de 6.7" a 120 Hz, Android 14 con MagicOS 8, procesador Octa-core, 8 GB de RAM y 256 GB de almacenamiento. Cuenta con cámara trasera de 108 MP + 2 MP, frontal de 8 MP y batería de hasta 6000 mAh.', 5899.01, 'https://acosa.com.hn/wp-content/uploads/2025/01/Alita-L33E1.webp', 'ACT', 3, 7),
  (18, 'Escritorio 39 Negro Wiwi 100X48X73.2Cm', 'El Escritorio 39 Negro Wiwi es un mueble compacto y funcional, ideal para espacios reducidos, oficinas en casa o áreas de estudio. Su diseño moderno y minimalista en color negro lo hace versátil para diferentes estilos de decoración.', 1434.00, 'https://acosa.com.hn/wp-content/uploads/2025/05/WI-ESC10048BLK.webp', 'ACT', 2, 10),
  (19, 'Audifono Redragon Gaming Lamia2 Usb 7.1 Negro Con Microfono Rgb H320', 'Los Lamia son auriculares RGB con sonido 7.1 virtual que destacan por tres atributos de construcción: son muy cómodos, son muy bonitos y son muy robustos. Pero hay mucho más en ellos; es en su rendimiento —tanto el de los auriculares como el del micrófono—donde descansan sus mayores virtudes. Con el software dedicado, además, incorporan poderosas herramientas de ecualización que acentúan y realzan la espacialidad del sonido.', 1894.99, 'https://acosa.com.hn/wp-content/uploads/2022/08/H320-RGB.jpg', 'ACT', 4, 6),
  (20, 'Televisor Aiwa Led 32 Smart HD', 'El Televisor Aiwa Led de 32″ Smart HD cuenta con sistema operativo Android TV, procesador doble Dual Core, 1.5GB de memoria DDR y 8GB de almacenamiento Flash. Viene con aplicaciones precargadas como Netflix, YouTube, Disney Plus, HBO Max, Facebook, Prime Video, entre otras, además de acceso a la tienda de aplicaciones Google Play Store para descargar tus apps favoritas.', 4199.00, 'https://acosa.com.hn/wp-content/uploads/2022/05/AW32B4SMG.jpg', 'ACT', 3, 4),
  (21, 'Calculadora Casio Fx-85Ms Cientifica 240 Fun 2-Linea', 'Este kit educativo incluye cálculos de fracciones, combinación y permutación, y herramientas para análisis estadístico como el editor de datos STAT, cálculo de desviación estándar y análisis de regresión. Soporta hasta 9 variables y viene acompañado de un estuche rígido deslizable para fácil transporte y protección del equipo.', 659.00, 'https://acosa.com.hn/wp-content/uploads/2022/11/FX85MS.jpg', 'ACT', 1, 5),
  (22, 'Lapicero Bluey 1 Depositos P2379', '¡Haz que escribir sea más divertido con el Lapicero Bluey 1 Depósito P2379! Diseñado con un colorido estampado de Bluey, el popular personaje infantil, este lapicero es ideal para niños y fans de la serie. Cuenta con un depósito de tinta de alta duración que ofrece un trazo suave y continuo. Su diseño ergonómico y liviano lo hace cómodo para el uso diario en la escuela o en casa. Perfecto para añadir un toque de alegría a cualquier estuche escolar.', 243.00, 'https://acosa.com.hn/wp-content/uploads/2025/02/D112-BLU-P2380.webp', 'ACT', 1, 42),
  (23, 'Termo Plastico Stitch 390Ml', 'Lindo y práctico termo con diseño de Stitch. Capacidad de 390 mL, ideal para agua o jugo. Ligero, resistente y con tapa segura para evitar derrames. Perfecto para niños y fans de Disney.', 198.00, 'https://acosa.com.hn/wp-content/uploads/2025/04/744-75005.webp', 'ACT', 1, 22),
  (24, 'Libro De Actividades Animales Divertidos Con Stickers Surt', 'Perfecto para que los niños aprendan jugando. Cuenta con páginas llenas de actividades coloridas y divertidos stickers para completar escenas de animales de la granja y la selva. Ideal para estimular la creatividad y el aprendizaje en los más pequeños.', 165.00, 'https://acosa.com.hn/wp-content/uploads/2024/08/SCA-5411.webp', 'ACT', 1, 5),
  (25, 'Rompecabeza Madera Reloj Merletto 1334', 'Este colorido rompecabezas de madera está diseñado para ayudar a los niños a aprender a leer la hora de manera divertida. Cuenta con manecillas móviles y números grandes, facilitando la comprensión de las horas y minutos. Ideal para niños a partir de 3 años, fomenta el desarrollo de habilidades motoras y cognitivas.', 210.50, 'https://acosa.com.hn/wp-content/uploads/2021/03/780-6801334.webp', 'ACT', 1, 2),
  (26, 'Borrador Y-Plus Butterfly Ex1307', 'borrador de alta calidad diseñado para eliminar trazos de lápiz con precisión y sin dañar el papel. Su diseño ergonómico y colores vibrantes lo hacen atractivo y fácil de usar. Ideal para estudiantes y profesionales que buscan un borrador confiable y duradero.', 13.30, 'https://acosa.com.hn/wp-content/uploads/2021/03/EX1307.webp', 'ACT', 1, 21),
  (27, 'Porta Carnet Plastico Deli Horizontal Gris', 'Protege tu carnet de identificación con este porta carnet plástico horizontal en color gris. Su diseño elegante y funcional te permite llevar tu documento de forma segura y visible en todo momento. Olvídate de preocuparte por perder tu carnet o dañarlo, este porta carnet es la solución ideal para mantener tu identificación siempre a mano.', 31.71, 'https://acosa.com.hn/wp-content/uploads/2022/11/8314GY.png', 'ACT', 2, 30),
  (28, 'Almohadilla Para Sello Azul #1 Merletto 11x7cm', 'Esta almohadilla de tinta azul de la marca Merletto es ideal para sellos manuales. Con un tamaño de 11x7 cm, ofrece una superficie amplia para obtener estampados nítidos y legibles. Su diseño compacto y práctico la hace perfecta para uso en oficinas, escuelas y negocios.', 29.80, 'https://acosa.com.hn/wp-content/uploads/2021/03/780-149326309.webp', 'ACT', 2, 9),
  (29, 'Binder 2 Risk Ampo', 'Carpeta de anillas de alta calidad, diseñada para ofrecer una organización eficiente y segura de documentos. Con una capacidad para aproximadamente 425 hojas, es ideal para uso en oficinas, escuelas y entornos profesionales que requieren almacenamiento confiable y duradero. Su estructura robusta y diseño funcional aseguran una larga vida útil y protección para tus documentos importantes.', 79.60, 'https://acosa.com.hn/wp-content/uploads/2025/05/POR-PT-00139.webp', 'ACT', 2, 35),
  (30, 'Papel Impresora 3 X150 1Parte Caja 50 Rollos', 'Este rollo de papel bond de 3 pulgadas de ancho y 150 pies de largo es ideal para impresoras de cocina, cajas registradoras y puntos de venta (POS). Con una capa de grosor adecuado, ofrece una impresión clara y nítida, siendo compatible con diversos modelos de impresoras. La caja contiene 50 rollos, lo que proporciona una solución económica y práctica para negocios con alto volumen de transacciones.', 1189.00, 'https://acosa.com.hn/wp-content/uploads/2023/02/R1-03150-1.jpg', 'ACT', 2, 26),
  (31, 'Anillos De Refuerzo Leitz', 'Adhesivos transparentes diseñados para reforzar los agujeros perforados en documentos, evitando que se desgasten o rasguen con el uso frecuente. Fabricados en película de polipropileno (PP), ofrecen una protección confiable y duradera. Son ideales para organizar y archivar documentos en carpetas de anillas, garantizando su integridad a lo largo del tiempo.', 105.90, 'https://acosa.com.hn/wp-content/uploads/2022/11/A1110.png', 'ACT', 2, 72),
  (32, 'Monitor Acer 21.5 Hd 1920 X 1080 Hdmi Vga Dp Ek220qh3bi Neg', 'Este monitor Full HD de 75 Hz con panel VA ofrece una buena calidad de imagen para oficina, estudio y entretenimiento básico. Cuenta con conectividad HDMI y VGA, montaje VESA, y tecnologías para proteger la vista como BlueLightShield y Flickerless.', 2445.00, 'https://acosa.com.hn/wp-content/uploads/2025/04/UM.WE0AA.301.webp', 'ACT', 3, 14),
  (33, 'Repetidor Cudy 2402Mbps Dual Band 5Ghz Wifi 6 Ax3000', 'Este extensor WiFi AX3000 con Wi-Fi 6 ofrece conexión rápida y estable gracias a su procesador Cortex-A53, antenas externas y tecnologías como OFDMA y MU-MIMO. Compatible con cualquier router, incluye puertos Gigabit Ethernet y funciones 3 en 1 (extensor, punto de acceso y malla), con configuración sencilla multilingüe.', 1395.00, 'https://acosa.com.hn/wp-content/uploads/2024/03/RE3000.webp', 'ACT', 3, 30),
  (33, 'Proyector Epson Powerlite 118', 'El proyector Epson Powerlite 118 ofrece resolución XGA nativa con tecnología 3LCD de 3 chips para colores brillantes y vivos. Cuenta con lámpara de larga duración de hasta 17,000 horas en modo ECO, conectividad avanzada RJ-45 y bajo consumo energético en modo de espera.', 19260.00, 'https://acosa.com.hn/wp-content/uploads/2023/06/V11HA03020.webp', 'ACT', 3, 9),
  (34, 'Panel Solar 560W Nenotech', 'El Panel Solar 560 W Nenotech (NS‑560MH‑144) ofrece alta potencia con tecnología monocristalina y tolerancia de +3 %, ideal para aplicaciones residenciales o comerciales. Con un voltaje en Pmax de 42,46 V y corriente de 13,19 A, soporta hasta 1500 V en sistemas y funciona en temperaturas de −40 °C a +85 °C. Su estructura robusta con marco de aluminio y garantía de 20 años lo hacen una opción confiable y duradera.', 5090.00, 'https://acosa.com.hn/wp-content/uploads/2024/06/NS-560MH-144.webp', 'ACT', 3, 5),
  (35, 'Parlante Marvo Gaming 2.0 3W Inalambrico Rgb Negro Sg-285', 'Altavoz para juegos con cable, ideal para PC o consolas. Ofrece sonido 2.0 con dos modos de audio, control de volumen mediante perilla práctica y 5 efectos de iluminación RGB para una experiencia más inmersiva. Diseño compacto y fácil de usar.', 395.00, 'https://acosa.com.hn/wp-content/uploads/2025/06/SG-285.webp', 'ACT', 4, 10),
  (36, 'Microfono Marvo Gaming 3.5Mm Streaming Negro Mic-06', 'El Micrófono Marvo Gaming MIC-06 es ideal para streaming, gaming o videollamadas. Cuenta con conexión USB, salida de 3.5 mm, soporte ajustable de 45°, iluminación RGB, cable trenzado de 1.7 m, malla superior de metal y base plástica resistente. Calidad y estilo para tus grabaciones.', 538.30, 'https://acosa.com.hn/wp-content/uploads/2023/09/MIC-06-BK.webp', 'ACT', 4, 9),
  (37, 'Memoria Ram Ddr4 Gaming 8Gb 3200Mhz Rgb Pc4-25600 Xpg D50', 'Alcanzando velocidades de hasta 4133 MHz y con una capacidad máxima de 32 GB, el módulo XPG SPECTRIX D50 es un monstruo de módulo de memoria. También tiene aspecto impactante con un elegante estilo geométrico y una impresionante barra de luz RGB triangular.', 1689.01, 'https://acosa.com.hn/wp-content/uploads/2021/12/AX4U32008G16A-ST5.jpg', 'ACT', 4, 15),
  (38, 'Mouse Redragon Gaming Griffin Usb Negro Rgb M607 Dpi 800-7200', 'El Redragon Griffin M607 es un mouse gaming con sensor óptico preciso y ajuste de DPI desde 800 hasta 7200. Ofrece una experiencia fluida y personalizable con iluminación RGB, diseño ergonómico y conexión USB alámbrica para un rendimiento confiable en cada partida.', 545.00, 'https://acosa.com.hn/wp-content/uploads/2021/09/M607.png', 'ACT', 4, 35),
  (39, 'Teclado T-Dagger Gaming Usb Negro RGB Full Size T-TGK310 Mecanico', 'El Teclado T-Dagger T-TGK310 es un teclado mecánico full size con switches T-Dagger Blue (50 g) o Red (45 g), ideal para gamers. Cuenta con iluminación RGB, teclas multimedia vía Fn, 100 % anti-ghosting y full key rollover. Con diseño robusto y conexión USB, ofrece precisión y estilo en cada partida.', 1117.00, 'https://acosa.com.hn/wp-content/uploads/2024/05/T-TGK310-RD-SP.webp', 'ACT', 4, 35);


--Datos en la tabla de Ventas
  INSERT INTO `sales` (`saleId`, `productId`, `discountPercent`, `saleStart`, `saleEnd`) VALUES
  (1, 1, 20.00, '2025-07-18 00:00:00', '2025-10-31 23:59:59'),
  (2, 8, 10.00, '2025-07-18 00:00:00', '2025-10-31 23:59:59'),
  (3, 12, 15.00, '2025-07-18 00:00:00', '2025-10-31 23:59:59'),
  (4, 16, 25.00, '2025-07-18 00:00:00', '2025-10-31 23:59:59'),
  (5, 17, 16.00, '2025-07-18 00:00:00', '2025-10-31 23:59:59'),
  (6, 18, 12.00, '2025-07-18 00:00:00', '2025-10-31 23:59:59'),
  (7, 20, 20.00, '2025-07-18 00:00:00', '2025-10-31 23:59:59'),
  (8, 21, 40.00, '2025-07-18 00:00:00', '2025-10-31 23:59:59');
